FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# ENV PORT=3001
# ENV REACT_APP_BACKEND_HOST=localhost:3000
EXPOSE 3001
# EXPOSE 3000
# CMD ["npm", "start", "--", "--host", "0.0.0.0"]
CMD ["npm", "start"]
